# Generated by Django 3.0.4 on 2020-03-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='lab_app.LabUser'),
        ),
        migrations.AddField(
            model_name='labuser',
            name='name',
            field=models.TextField(default='Иван Иванов'),
        ),
    ]
